### ISSUE TITLE
Certain Useful improvements needed

### ISSUE THREAD

**Issue by Arijeet2580** [Arijeet2580/Food_catering_Website#1]
You may add JavaScript to this website or make it more compatible and responsive Website

**Comment by Alessandro-Battiato** [comment]
Greetings! May I ask you more informations as to what you're asking for? Maybe a specific functionality or something else, I'm interested in working on this issue

**Comment by Arijeet2580** [comment]
I think a three-bar icon and improving the back to top button will be nice to add in the project as my back to top button brings the page to Home section.

**Comment by Alessandro-Battiato** [comment]
2 more questions and I'll work right on it, 
- 1: With the three bar icon are you suggesting to implement a burger menu for smaller devices so that all the links are displayed in a window once you click the burger icon or you meant something else?
- 2: I can't actually see a back to top button aside from the top left icon with a hand holding an ice cream cone and once clicked it doesn't bring me to the home section but rather to the Contact us section, if you want I can implement another button that stays fixed on the bottom right corner of the page and once clicked it brings you to the top, or I could work on the already existing button and fix it to bring you to the top of the page once clicked

**Comment by Arijeet2580** [comment]
1: Yes, I actually thought about this for smaller device but can not specify it earlier 
2: Yes, change the ice cream icon to go to the home section and make the back_to_top button on left. 
3: This is my first project on web dev if you please correct the errors on the code and I will work my level best on this project too. 

Thanks for working on it. @Alessandro-Battiato

**Comment by Alessandro-Battiato** [comment]
Alright I'll open a pull request as soon as everything's ready, though don't expect top tier code as my experience isn't that far beyond yours :)

**Comment by Alessandro-Battiato** [comment]
There's a problem regarding the button to scroll to the top, looking closely to your html file I can now see that there is actually an existing button:  <button id="scrollback">
      <a href="#home"
        ><img src="img/top-scroll-icon.png" alt="" id="scrollbtn"
      /></a>
    </button>
But I could not see it anywhere because your project is missing the image, are you able to pass it to me so I can work on it or should I delete the image and style the button alone with css?

**Comment by Alessandro-Battiato** [comment]
There's a problem regarding the button to scroll to the top, looking closely to your html file I can now see that there is actually an existing button:

 <button id="scrollback">
      <a href="#home"
        ><img src="img/top-scroll-icon.png" alt="" id="scrollbtn"
      /></a>
    </button>

But I could not see it anywhere because your project is missing the image, are you able to pass it to me so I can work on it or should I delete the image and style the button alone with css?

**Comment by Alessandro-Battiato** [comment]
There's a problem regarding the button to scroll to the top, looking closely to your html file I can now see that there is actually an existing button, called with the id of "scrollback".
But I could not see it anywhere because your project is missing the image, are you able to pass it to me so I can work on it or should I delete the image and style the button alone with css?

**Comment by Arijeet2580** [comment]
The image is not present in my device it may got deleted earlier please change the image for scrollback.

**Comment by Alessandro-Battiato** [comment]
I completed my task successfully, opened the related pr :)
Also I suggest you using Prettier as an extension on your code editor, all of the code was indented automatically by Prettier in my editor so everything looks "prettier" now
